"""initial

Revision ID: 305d859b115e
Revises: 
Create Date: 2026-04-13 16:07:08.432473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305d859b115e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chatpaat_app_customuser_user_permissions_customuser_id_9c1e5c15'), table_name='chatpaat_app_customuser_user_permissions')
    op.drop_index(op.f('chatpaat_app_customuser_user_permissions_permission_id_8c9b34ca'), table_name='chatpaat_app_customuser_user_permissions')
    op.drop_table('chatpaat_app_customuser_user_permissions')
    # Drop dependent tables first (they have FKs to auth_group)
    op.drop_index(op.f('chatpaat_app_customuser_groups_customuser_id_8a3cef39'), table_name='chatpaat_app_customuser_groups')
    op.drop_index(op.f('chatpaat_app_customuser_groups_group_id_01b7fd53'), table_name='chatpaat_app_customuser_groups')
    op.drop_table('chatpaat_app_customuser_groups')
    op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    # Now drop auth_group (no more dependent tables)
    op.drop_index(op.f('auth_group_name_a6ea08ec_like'), table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_table('django_content_type')
    # Drop foreign key constraints BEFORE altering column types
    op.drop_constraint(op.f('chatpaat_app_chatmes_chat_id_6bade942_fk_chatpaat_'), 'chatpaat_app_chatmessage', type_='foreignkey')
    # Now alter column types
    op.alter_column('chatpaat_app_chat', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chatpaat_app_chatmessage', 'chat_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # Continue with other alterations
    op.alter_column('chatpaat_app_chat', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('chatpaat_app_chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('chatpaat_app_chat', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('chatpaat_app_chat_user_id_4181dcd8'), table_name='chatpaat_app_chat')
    op.create_index(op.f('ix_chatpaat_app_chat_user_id'), 'chatpaat_app_chat', ['user_id'], unique=False)
    op.drop_constraint(op.f('chatpaat_app_chat_user_id_4181dcd8_fk_chatpaat_'), 'chatpaat_app_chat', type_='foreignkey')
    op.create_foreign_key(None, 'chatpaat_app_chat', 'chatpaat_app_customuser', ['user_id'], ['id'])
    op.alter_column('chatpaat_app_chatmessage', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('chatpaat_app_chatmessage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('chatpaat_app_chatmessage_chat_id_6bade942'), table_name='chatpaat_app_chatmessage')
    op.create_index(op.f('ix_chatpaat_app_chatmessage_chat_id'), 'chatpaat_app_chatmessage', ['chat_id'], unique=False)
    op.create_foreign_key(None, 'chatpaat_app_chatmessage', 'chatpaat_app_chat', ['chat_id'], ['id'])
    op.alter_column('chatpaat_app_customuser', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('chatpaat_app_customuser', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chatpaat_app_customuser', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chatpaat_app_customuser', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chatpaat_app_customuser', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('chatpaat_app_customuser', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('chatpaat_app_customuser_email_b3940c18_like'), table_name='chatpaat_app_customuser')
    op.drop_constraint(op.f('chatpaat_app_customuser_email_key'), 'chatpaat_app_customuser', type_='unique')
    op.drop_index(op.f('chatpaat_app_customuser_username_24374871_like'), table_name='chatpaat_app_customuser')
    op.drop_constraint(op.f('chatpaat_app_customuser_username_key'), 'chatpaat_app_customuser', type_='unique')
    op.create_index(op.f('ix_chatpaat_app_customuser_email'), 'chatpaat_app_customuser', ['email'], unique=True)
    op.create_index(op.f('ix_chatpaat_app_customuser_username'), 'chatpaat_app_customuser', ['username'], unique=True)
    op.alter_column('chatpaat_app_passwordresettoken', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('chatpaat_app_passwordresettoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('chatpaat_app_passwordresettoken', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_chatpaat_app_passwordresettoken_token_hash'), 'chatpaat_app_passwordresettoken', ['token_hash'], unique=False)
    op.create_index(op.f('ix_chatpaat_app_passwordresettoken_user_id'), 'chatpaat_app_passwordresettoken', ['user_id'], unique=False)
    op.drop_constraint(op.f('chatpaat_app_passwordresettoken_user_id_fkey'), 'chatpaat_app_passwordresettoken', type_='foreignkey')
    op.create_foreign_key(None, 'chatpaat_app_passwordresettoken', 'chatpaat_app_customuser', ['user_id'], ['id'])
    op.alter_column('chatpaat_app_usersearchhistory', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('chatpaat_app_usersearchhistory', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('chatpaat_app_usersearchhistory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('chatpaat_app_usersearchhistory_user_id_8b08f52e'), table_name='chatpaat_app_usersearchhistory')
    op.create_index(op.f('ix_chatpaat_app_usersearchhistory_user_id'), 'chatpaat_app_usersearchhistory', ['user_id'], unique=False)
    op.drop_constraint(op.f('chatpaat_app_usersea_user_id_8b08f52e_fk_chatpaat_'), 'chatpaat_app_usersearchhistory', type_='foreignkey')
    op.create_foreign_key(None, 'chatpaat_app_usersearchhistory', 'chatpaat_app_customuser', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatpaat_app_usersearchhistory', type_='foreignkey')
    op.create_foreign_key(op.f('chatpaat_app_usersea_user_id_8b08f52e_fk_chatpaat_'), 'chatpaat_app_usersearchhistory', 'chatpaat_app_customuser', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_chatpaat_app_usersearchhistory_user_id'), table_name='chatpaat_app_usersearchhistory')
    op.create_index(op.f('chatpaat_app_usersearchhistory_user_id_8b08f52e'), 'chatpaat_app_usersearchhistory', ['user_id'], unique=False)
    op.alter_column('chatpaat_app_usersearchhistory', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chatpaat_app_usersearchhistory', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chatpaat_app_usersearchhistory', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'chatpaat_app_passwordresettoken', type_='foreignkey')
    op.create_foreign_key(op.f('chatpaat_app_passwordresettoken_user_id_fkey'), 'chatpaat_app_passwordresettoken', 'chatpaat_app_customuser', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chatpaat_app_passwordresettoken_user_id'), table_name='chatpaat_app_passwordresettoken')
    op.drop_index(op.f('ix_chatpaat_app_passwordresettoken_token_hash'), table_name='chatpaat_app_passwordresettoken')
    op.alter_column('chatpaat_app_passwordresettoken', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chatpaat_app_passwordresettoken', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('chatpaat_app_passwordresettoken', 'token_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_chatpaat_app_customuser_username'), table_name='chatpaat_app_customuser')
    op.drop_index(op.f('ix_chatpaat_app_customuser_email'), table_name='chatpaat_app_customuser')
    op.create_unique_constraint(op.f('chatpaat_app_customuser_username_key'), 'chatpaat_app_customuser', ['username'])
    op.create_index(op.f('chatpaat_app_customuser_username_24374871_like'), 'chatpaat_app_customuser', ['username'], unique=False)
    op.create_unique_constraint(op.f('chatpaat_app_customuser_email_key'), 'chatpaat_app_customuser', ['email'])
    op.create_index(op.f('chatpaat_app_customuser_email_b3940c18_like'), 'chatpaat_app_customuser', ['email'], unique=False)
    op.alter_column('chatpaat_app_customuser', 'date_joined',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chatpaat_app_customuser', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chatpaat_app_customuser', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chatpaat_app_customuser', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chatpaat_app_customuser', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chatpaat_app_customuser', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'chatpaat_app_chatmessage', type_='foreignkey')
    op.create_foreign_key(op.f('chatpaat_app_chatmes_chat_id_6bade942_fk_chatpaat_'), 'chatpaat_app_chatmessage', 'chatpaat_app_chat', ['chat_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_chatpaat_app_chatmessage_chat_id'), table_name='chatpaat_app_chatmessage')
    op.create_index(op.f('chatpaat_app_chatmessage_chat_id_6bade942'), 'chatpaat_app_chatmessage', ['chat_id'], unique=False)
    op.alter_column('chatpaat_app_chatmessage', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chatpaat_app_chatmessage', 'chat_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chatpaat_app_chatmessage', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'chatpaat_app_chat', type_='foreignkey')
    op.create_foreign_key(op.f('chatpaat_app_chat_user_id_4181dcd8_fk_chatpaat_'), 'chatpaat_app_chat', 'chatpaat_app_customuser', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_chatpaat_app_chat_user_id'), table_name='chatpaat_app_chat')
    op.create_index(op.f('chatpaat_app_chat_user_id_4181dcd8'), 'chatpaat_app_chat', ['user_id'], unique=False)
    op.alter_column('chatpaat_app_chat', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chatpaat_app_chat', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('chatpaat_app_chat', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('chatpaat_app_chat', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'))
    )
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'))
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('chatpaat_app_customuser_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['chatpaat_app_customuser.id'], name=op.f('chatpaat_app_customu_customuser_id_8a3cef39_fk_chatpaat_'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('chatpaat_app_customu_group_id_01b7fd53_fk_auth_grou'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chatpaat_app_customuser_groups_pkey')),
    sa.UniqueConstraint('customuser_id', 'group_id', name=op.f('chatpaat_app_customuser__customuser_id_group_id_ec363fb5_uniq'))
    )
    op.create_index(op.f('chatpaat_app_customuser_groups_group_id_01b7fd53'), 'chatpaat_app_customuser_groups', ['group_id'], unique=False)
    op.create_index(op.f('chatpaat_app_customuser_groups_customuser_id_8a3cef39'), 'chatpaat_app_customuser_groups', ['customuser_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_permission_pkey')),
    sa.UniqueConstraint('content_type_id', 'codename', name=op.f('auth_permission_content_type_id_codename_01ab375a_uniq'))
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('auth_group_name_key'))
    )
    op.create_index(op.f('auth_group_name_a6ea08ec_like'), 'auth_group', ['name'], unique=False)
    op.create_table('chatpaat_app_customuser_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['chatpaat_app_customuser.id'], name=op.f('chatpaat_app_customu_customuser_id_9c1e5c15_fk_chatpaat_'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('chatpaat_app_customu_permission_id_8c9b34ca_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chatpaat_app_customuser_user_permissions_pkey')),
    sa.UniqueConstraint('customuser_id', 'permission_id', name=op.f('chatpaat_app_customuser__customuser_id_permission_db6a95a5_uniq'))
    )
    op.create_index(op.f('chatpaat_app_customuser_user_permissions_permission_id_8c9b34ca'), 'chatpaat_app_customuser_user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('chatpaat_app_customuser_user_permissions_customuser_id_9c1e5c15'), 'chatpaat_app_customuser_user_permissions', ['customuser_id'], unique=False)
    # ### end Alembic commands ###
